[package]
name = "luffy"
version = "0.2.2"
edition = "2021"
authors = ["Liang Huang <liang.huang@marinethinking.com>"]
description = "A smart vehicle onboard program that provides network connectivity and web-based monitoring/control interface"
license = "MIT"

[dependencies]
anyhow = "1.0"
askama = "0.12"
aws-config = {version = "1.5", features = ["rustls"]}
aws-sdk-dynamodb = {version = "1.54", features = ["rustls"]}
aws-sdk-lambda = {version = "1.59", features = ["rustls"]}
aws-sdk-s3 = {version = "1.63.0", features = ["rustls"]}
axum = "0.7"
config = "0.14"
dirs = "5.0"
mac_address = "1.1"
mavlink = "0.13"
num-traits = "0.2"
once_cell = "1.20"
rumqttc = {version = "0.24", features = ["use-rustls"]}
rumqttd = {version = "0.19", features = ["use-rustls"]}
rustls-pemfile = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.41", features = ["full"] }
tower-http = { version = "0.6", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.11", features = ["v4"] }
self_update = "0.41"
semver = "1.0"
reqwest = { version = "0.12", features = ["stream","rustls-tls"] }
chrono = "0.4"
indicatif = "0.17"
futures-util = "0.3"


[dev-dependencies]
tempfile = "3.14"

[lib]
name = "luffy"
path = "src/lib.rs"

[package.metadata.deb]
maintainer = "Liang Huang <liang.huang@marinethinking.com>"
copyright = "2024, Marine Thinking"
license-file = ["LICENSE", "4"]
extended-description = """
A smart vehicle onboard program that provides network connectivity 
and web-based monitoring/control interface.
Features include MQTT broker, web server, telemetry, and command control.
"""
depends = "$auto"
section = "utility"
priority = "optional"
maintainer-scripts = "debian/"
assets = [
    ["target/release/luffy", "usr/bin/", "755"],
    ["config/dev.toml", "etc/luffy/", "644"],
    ["scripts/luffy.service", "etc/systemd/system/", "644"],
]

[profile.release]
lto = 'thin'  # Faster than full LTO
codegen-units = 16  # More parallel compilation
opt-level = 2  # Good balance of speed vs size
