[package]
name = "luffy"
version = "0.2.1"
edition = "2021"
authors = ["Liang Huang <liang.huang@marinethinking.com>"]
description = "A smart vehicle onboard program that provides network connectivity and web-based monitoring/control interface"
license = "MIT"

[dependencies]
anyhow = "1.0"
askama = "0.12"
aws-config = "1.5"
aws-sdk-dynamodb = "1.54"
aws-sdk-lambda = "1.59"
aws-sdk-secretsmanager = "1.53"
aws-sdk-s3 = "1.63.0"
axum = "0.7"
config = "0.14"
dirs = "5.0"
mac_address = "1.1"
mavlink = "0.13"
num-traits = "0.2"
once_cell = "1.20"
rumqttc = "0.24"
rumqttd = "0.19"
rustls-pemfile = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.41", features = ["full"] }
tower-http = { version = "0.6", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.11", features = ["v4"] }
self_update = "0.41"
semver = "1.0"
reqwest = { version = "0.12", features = ["json"] }
chrono = "0.4.38"
indicatif = "0.17.9"
octocrab = "0.42.1"
bytes = "1.9.0"


[dev-dependencies]
tempfile = "3.14"

[lib]
name = "luffy"
path = "src/lib.rs"

[package.metadata.deb]
maintainer = "Liang Huang <liang.huang@marinethinking.com>"
copyright = "2024, Marine Thinking"
license-file = ["LICENSE", "4"]
extended-description = """
A smart vehicle onboard program that provides network connectivity 
and web-based monitoring/control interface.
Features include MQTT broker, web server, telemetry, and command control.
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/luffy", "usr/bin/", "755"],
    ["config/dev.toml", "etc/luffy/config.toml", "644"],
    ["scripts/luffy.service", "etc/systemd/system/luffy.service", "644"],
]