[package]
name = "luffy-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
config.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
rumqttc.workspace = true
glob.workspace = true
strum.workspace = true
strum_macros.workspace = true
 
futures = "0.3"
network-interface = "2.0"
uuid = { version = "1.11", features = ["v4"] }
reqwest = { version = "0.12", features = ["json"] }
semver = "1.0"
