#!/bin/sh
set -e

# Create luffy user and group if they don't exist
if ! getent group luffy >/dev/null; then
    addgroup --system luffy
fi
if ! getent passwd luffy >/dev/null; then
    adduser --system --ingroup luffy --no-create-home --shell /usr/sbin/nologin luffy
fi

# Set permissions
chown -R luffy:luffy /etc/luffy
chmod 755 /usr/bin/luffy

# Reload systemd
systemctl daemon-reload

# Enable service (but don't start it)
systemctl enable luffy.service

#DEBHELPER#
exit 0 