[feature]
local_iot = false
remote_iot = false
broker = false
mavlink = false
ota = true

[general]
# TRACE, DEBUG, INFO, WARN, ERROR
log_level = "info"
vehicle_id = "liang-test"

[aws]
region = "ca-central-1"

[aws.iot]
root_ca_path = "certs/AmazonRootCA.pem"
endpoint = "a1w2o8b6t3ahv7-ats.iot.ca-central-1.amazonaws.com"
port = 8883

[aws.lambda]
register = "arn:aws:lambda:ca-central-1:583818069008:function:amplify-d34e88yymcb7ax-de-registerIotThinglambdaCE-j14AZkH1hKNp"


[iot]
local_interval = 1 # seconds
remote_interval = 4 # seconds

[broker]
host = "127.0.0.1"
port = 9183  # needs to be same with rumqttd.toml

[mavlink]
connection_string = "udpin:192.168.20.183:14559"  

[web]
host = "0.0.0.0"
port = 9000

[ota]
strategy = "Auto"  # "Auto", "Manual", or "Disabled"
check_interval = 3600  # when strategy is "Auto"
version_check_url = "https://registry.hub.docker.com/v2/repositories/mt2025/luffy/tags?page_size=100"
image_name = "mt2025/luffy"


