log_level = "debug"

[feature]
local_iot = true
remote_iot = true
broker = true
mavlink = true

[mavlink]
connection_string = "udpin:192.168.20.153:14559"

[ota]
enable = true
strategy = "manual"  # auto, manual, or disabled
check_interval = 3600  # seconds
download_dir = "/home/luffy/.deb"
github_repo = "Marinethinking/luffy"
launcher = true  # whether to update luffy-launcher

[iot]
local_interval = 3
remote_interval = 3

