log_level = "info"

[web]
host = "0.0.0.0"
port = 9000

[ota]
strategy = "auto"  # or "manual" or "disabled"
check_interval = 3600  # in seconds
github_repo = "Marinethinking/luffy"
gateway=true
media=true
download_dir = "/home/luffy/.deb/"
