name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      
      - name: Install cargo-deb
        run: cargo install cargo-deb
      
      - name: Configure ARM64 repositories
        run: |
          sudo dpkg --add-architecture arm64
          sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
          sudo tee /etc/apt/sources.list << EOF
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse
          EOF
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
      
      - name: Install dependencies
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config
          sudo apt-get install -y libssl-dev:arm64
          sudo apt-get install -y binutils-aarch64-linux-gnu
      
      - name: Prepare files
        run: |
          mkdir -p target/debian/etc/luffy
          mkdir -p target/debian/etc/systemd
          mkdir -p target/debian/DEBIAN
          cp config/dev.toml target/debian/etc/luffy/
          cp scripts/luffy.service target/debian/etc/systemd/luffy.service
          cp scripts/postinst target/debian/DEBIAN/postinst
          chmod 755 target/debian/DEBIAN/postinst
      
      - name: Build and package
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          OPENSSL_DIR: /usr/lib/aarch64-linux-gnu
          OPENSSL_INCLUDE_DIR: /usr/include/aarch64-linux-gnu
          OPENSSL_LIB_DIR: /usr/lib/aarch64-linux-gnu
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_INCREMENTAL: 1
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo deb --target aarch64-unknown-linux-gnu --no-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/aarch64-unknown-linux-gnu/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:1.75-slim  # Smaller image, faster to pull