name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      
      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          cargo install cargo-deb
      
      - name: Build and package
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo deb --target aarch64-unknown-linux-gnu --no-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/aarch64-unknown-linux-gnu/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 