name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: ubuntu-latest
    container: 
      image: rust:1.75-slim
    steps:
      - name: Configure ARM64 repositories
        run: |
          apt-get update
          apt-get install -y sudo
          dpkg --add-architecture arm64
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list
          apt-get update
      
      - name: Install dependencies
        run: |
          apt-get install -y --no-install-recommends \
            gcc-aarch64-linux-gnu \
            pkg-config \
            libssl-dev:arm64 \
            binutils-aarch64-linux-gnu \
            ca-certificates \
            libc6-dev-arm64-cross
          cargo install cargo-deb

  build:
    needs: setup
    runs-on: ubuntu-latest
    container: 
      image: rust:1.75-slim
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Prepare files
        run: |
          mkdir -p target/debian/{etc/luffy,etc/systemd/system,DEBIAN}
          cp config/dev.toml target/debian/etc/luffy/
          cp scripts/luffy.service target/debian/etc/systemd/system/
          cp debian/postinst target/debian/DEBIAN/postinst
          cp debian/control target/debian/DEBIAN/control
          chmod 755 target/debian/DEBIAN/postinst
      
      - name: Build
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          OPENSSL_DIR: /usr/lib/aarch64-linux-gnu
          OPENSSL_INCLUDE_DIR: /usr/include/aarch64-linux-gnu
          OPENSSL_LIB_DIR: /usr/lib/aarch64-linux-gnu
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_INCREMENTAL: 1
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo deb --target aarch64-unknown-linux-gnu --no-build
      
      - name: Test
        run: cargo test --all

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/aarch64-unknown-linux-gnu/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}