name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config libssl-dev:arm64 libssl-dev
      
      - name: Prepare files
        run: |
          mkdir -p target/debian/etc/luffy
          mkdir -p target/debian/etc/systemd
          cp config/dev.toml target/debian/etc/luffy/
          cp scripts/luffy.service target/debian/etc/systemd/luffy.service
      
      - name: Build and package
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          OPENSSL_DIR: /usr/lib/ssl
          PKG_CONFIG_PATH: /usr/lib/aarch64-linux-gnu/pkgconfig
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo deb --target aarch64-unknown-linux-gnu --no-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/aarch64-unknown-linux-gnu/debian/*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 